# Generated by Django 2.1.7 on 2019-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayOff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
